######## CLACK ###################################
- id: zoutniveau_alarm_melding
  alias: Zoutniveau alarm melding
  trigger:
  - platform: state
    entity_id: sensor.zout_bijvullen
    to: ja
  condition: []
  action:
  - service: notify.mobile_app_iphone_van_a_c_a
    data:
      title: Let op!
      message: Zout niveau van ontharder is laag! Vandaag gaan bijvullen!
      data:
        push:
          sound:
            name: default
            critical: 1
            volume: 1
  initial_state: 'true'
  mode: single
####################################################
- id: water_softener_pulse_received
  alias: Water softener - Pulse Received
  trigger:
  - platform: state
    entity_id:
    - sensor.watermeter_stand
  condition: []
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.water_softener_meter_liters
      value: '{{ (states.sensor.watermeter_stand.state | int ) }}'
  initial_state: true
####################################################
- id: set_water_softener_start_backwash
  alias: Set water softener start Backwash
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.regeneratie_pulse
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.water_softener_status
      state: Idle
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.water_softener_status
      option: Backwash
  - service: timer.start
    entity_id: timer.timer_ws_backwash
  - service: timer.start
    entity_id: timer.timer_ws_total
  initial_state: true
####################################################
- id: set_water_softener_start_brine
  alias: Set water softener start Brine
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_ws_backwash
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.water_softener_status
      state: Backwash 1st
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.water_softener_status
      option: Brine
  - service: timer.start
    entity_id: timer.timer_ws_brine
  initial_state: true
####################################################
- id: set_water_softener_start_rinse
  alias: Set water softener start Rinse
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_ws_brine
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.water_softener_status
      state: Backwash
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.water_softener_status
      option: Rinse
  - service: timer.start
    entity_id: timer.timer_ws_rinse
  initial_state: true
####################################################
- id: set_water_softener_start_fill
  alias: Set water softener start Fill
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_ws_rinse
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.water_softener_status
      state: Rinse
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.water_softener_status
      option: Fill
  - service: timer.start
    entity_id: timer.timer_ws_fill
  initial_state: true
####################################################
- id: set_water_softener_idle
  alias: Set water softener Idle
  trigger:
  - platform: event
    event_type: timer.finished
    event_data:
      entity_id: timer.timer_ws_fill
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_select.water_softener_status
      state: Fill
  action:
  - service: input_select.select_option
    data:
      entity_id: input_select.water_softener_status
      option: Idle
  - service: esphome.clack_meterstand_clack
    data:
      meter_value: 0
  - service: input_number.set_value
    data_template:
      entity_id: input_number.water_softener_meter_liters
      value: 0
  initial_state: true
####################################################
- id: set_new_watermeter_value
  alias: Set new watermeter value
  trigger:
  - platform: state
    entity_id:
    - input_number.water_softener_meter_liters
  condition: []
  action:
  - service: esphome.meterstand_clack
    data:
      meter_value: '{{ (states.input_number.water_softener_meter_liters.state | int
        ) }}'