views:
  - title: Ontharder
    path: ontharder
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - cards:
              - type: entities
                entities:
                  - entity: input_number.water_softener_meter_liters
                    type: custom:multiple-entity-row
                    icon: mdi:cup-water
                    name: Water ontharder
                    secondary_info:
                      entity: input_select.water_softener_status
                      name: 'cycle: '
                    state_header: verbr.
                    entities:
                      - entity: sensor.water_softener_days_left
                        name: nog dag
                      - entity: sensor.water_softener_m3_left
                        name: nog m3
                style: |
                  ha-card {
                    border-radius: 20px
                  }
                  .card-header {
                    font-size: 18px;
                    padding: 5px 25px;
                    font-weight: bold;
                  }          
                title: Water ontharder
              - entities:
                  - entity: sensor.water_softener_l_left
                    max: 4000
                    min: 0
                    name: Ltr gebruikt
                height: 8px
                decimal: false
                positions:
                  icon: 'off'
                  indicator: 'off'
                  tap_action: info
                  name: 'off'
                  value: 'off'
                style: |
                  ha-card {
                    border-radius: 20px
                  }
                  .card-content {
                   padding: 0px 10px 10px 10px;
                   }      
                type: custom:bar-card
            mode: vertical
            type: custom:stack-in-card
          - type: conditional
            conditions:
              - entity: timer.timer_ws_total
                state_not: idle
            card:
              type: entities
              style: |

                .card-content {
                  padding: 8px;
                }
                .card-content > div {
                  margin: 0 !important;
                }  
                .card-header {
                  font-size: 18px;
                  padding: 5px 25px;
                  font-weight: bold;
                }  
                    .card-header {
                      font-size: 18px;
                      padding: 5px 25px;
                      font-weight: bold;
                    }     
              title: Regen. gestart
              entities:
                - conditions:
                    - entity: timer.timer_ws_backwash1
                      state_not: idle
                  row:
                    entity: timer.timer_ws_backwash1
                    icon: mdi:numeric-1-circle
                    name: 'Cycle: Backwash 1st'
                  type: conditional
                - conditions:
                    - entity: timer.timer_ws_brine
                      state_not: idle
                  row:
                    entity: timer.timer_ws_brine
                    icon: mdi:numeric-2-circle
                    name: 'Cycle: Brine'
                  type: conditional
                - conditions:
                    - entity: timer.timer_ws_backwash
                      state_not: idle
                  row:
                    entity: timer.timer_ws_backwash
                    icon: mdi:numeric-3-circle
                    name: 'Cycle: Backwash 2nd'
                  type: conditional
                - conditions:
                    - entity: timer.timer_ws_rinse
                      state_not: idle
                  row:
                    entity: timer.timer_ws_rinse
                    icon: mdi:numeric-4-circle
                    name: 'Cycle: Rinse'
                  type: conditional
                - conditions:
                    - entity: timer.timer_ws_fill
                      state_not: idle
                  row:
                    entity: timer.timer_ws_fill
                    icon: mdi:numeric-5-circle
                    name: 'Cycle: Fill'
                  type: conditional
                - type: section
                - entity: timer.timer_ws_total
                  icon: mdi:timer-sand
                  name: Total time left (5 cycles)
      - type: entities
        entities:
          - entity: sensor.watermeter_stand
          - entity: sensor.water_softener_l_left
            name: Waterontharder ltr over
          - entity: sensor.water_softener_m3_left
            name: Waterontharder m3 over
          - entity: sensor.clack_afstand
            name: Afstand
          - entity: sensor.clack_hoogte
            name: Hoogte
          - entity: sensor.clack_procent
            name: Procent
          - entity: sensor.zout_bijvullen
          - entity: sensor.clack_geregenereerd_op
          - entity: sensor.laatste_regeneratie_uren
          - entity: sensor.laatste_regeneratie_dagen
          - entity: binary_sensor.watermeter_pulse
          - entity: binary_sensor.regeneratie_pulse
        title: Clack
      - elements:
          - entity: sensor.salt_level
            image: local/images/softener.png
            state_image:
              softener_100: local/images/softener100.png
              softener_80: local/images/softener80.png
              softener_60: local/images/softener60.png
              softener_40: local/images/softener40.png
              softener_20: local/images/softener20.png
              softener_10: local/images/softener10.png
              softener_0: local/images/softener0.png
              'off': local/images/softener0.png
            style:
              left: 0%
              top: 0%
              transform: scale(1,1)
            tap_action:
              action: none
            type: image
        image: local/images/softener.png
        panel: true
        type: picture-elements
      - type: entities
        entities:
          - entity: sensor.waterverbruik_dit_kwartier
          - entity: sensor.waterverbruik_dit_uur
          - entity: sensor.waterverbruik_vandaag
          - entity: sensor.waterverbruik_maand
          - entity: sensor.waterverbruik_jaar
      - type: custom:apexcharts-card
        graph_span: 7d
        update_interval: 5m
        cache: true
        span:
          end: day
          offset: '-1sec'
        header:
          show: true
          title: Water per dag
        apex_config:
          xaxis:
            labels:
              format: dd-MM
              show: true
              showAlways: true
          yaxis:
            forceNiceScale: true
            decimalsInFloat: 0
            min: 0
          chart:
            type: area
            height: 300
          stroke:
            show: true
            width: 1
          legend:
            show: true
          dataLabels:
            enabled: false
            distributed: true
          fill:
            type: gradient
            gradient:
              shadeIntensity: 0.1
              opacityFrom: 0.25
              opacityTo: 1
              inverseColors: true
              stops:
                - 0
                - 90
                - 100
        series:
          - entity: sensor.waterverbruik_vandaag
            name: Verbruik
            type: column
            float_precision: 2
            group_by:
              func: max
              duration: 23h59m59s
      - type: entities
        entities:
          - entity: number.min_afstand_zout
          - entity: number.max_afstand_zout
          - entity: number.zout_bijvullen_afstand
          - entity: number.capaciteit_in_dagen
          - entity: number.capaciteit_in_liters
          - entity: sensor.versie
          - entity: sensor.clack_ip
        title: Instellingen