substitutions:
  clack_distance: Afstand
  clack_procent: Procent
  clack_heigth: Hoogte
  clack_watermeter_total: Watermeter stand
  clack_m3_left: Waterontharder m3 over
  clack_l_left: Waterontharder ltr over
  clack_version: Versie
  clack_regeneration_last: Waterontharder geregenereerd op
  clack_fill_salt: Zout bijvullen
  clack_saltlevel_height_min: Min afstand zout
  clack_saltlevel_height_max: Max afstand zout
  clack_saltlevel_height_fill: Zout bijvullen afstand
  clack_capacity_liters: Capaciteit in liters
  clack_capacity_days: Capaciteit in dagen
  clack_watermeter_pulse: Watermeter pulse
  clack_regeneration_pulse: Regeneratie pulse
  auto: Auto
  initialializating: Initialisatie
  unknown: Onbekend
  hours: uur
  days: dagen
  yes: ja
  no: nee
  jan: jan
  feb: feb
  Mar: maart
  Apr: april
  Mai: mei
  Jun: juni
  Jul: juli
  Aug: aug
  Sep: sept
  Okt: okt
  Nov: nov
  Dec: dec
  Mon: ma
  Tue: Di
  Wed: wo
  Thu: do
  Fri: vrij
  Sat: sat
  Sun: zon