substitutions:
  salt_level_distance: Saltlevel distance
  salt_level_procent: Saltlevel procent
  salt_level_height: Saltlevel height
  salt_level_version: Version
  salt_level_regeneration_last: Watersoftener generated on
  salt_level_fill_salt: Fill salt
  salt_level_height_min: Min distance salt
  salt_level_height_max: Max distance salt
  salt_level_height_fill: Fill salt distance
  salt_level_ip: Salt level IP
  salt_level_wifi_signal_db: WiFi Signal dB
  salt_level_wifi_signal_db_percent: WiFi Signal
  salt_level_uptime: Uptime
  hours: hours
  days: days
  salt_level_yes: "yes"
  salt_level_no: "no"

text_sensor:
  # Expose last regeneration information as sensor / already in English
  - platform: template
    name: ${salt_level_regeneration_last}
    id: salt_level_regeneration_last
    icon: mdi:clock-start
    update_interval: never