### ESP32 used is a MH-ET-LIVE, also known as Wemos D32 Mini 
### https://www.bitsandparts.nl/MH-ET-Live-MiniKit-ESP32-WiFi-Buetooth-ontwikkelboard-p1905277

esp32:
  board: mhetesp32minikit
  framework:
    type: arduino

uart:
  id: uart_bus
  tx_pin: 21
  rx_pin: 22
  baud_rate: 9600

substitutions:
  gpio_pin_pulse_meter: 16 # wemos d1 mini -D4
  gpio_pin_pulse_regen: 18 ## wemos d1 mini - D5


# Enable/Disable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    dht.sensor: WARN
    switch: WARN
    button: WARN
    number: WARN
  # baud_rate: 0  # <--- super important! for ESP8266

wifi:
  ap:
    ssid: "${name} hotspot"
    password: "configesp"

captive_portal:

# Enable Web server.
web_server:
  port: 80
