### ESP32S3 used is a Lilygo T7-S3
### https://www.tindie.com/products/lilygo/lilygo-t7-s3-esp32-s3-development-board/

esp32:
  board: adafruit_feather_esp32s3_nopsram
  framework:
    type: arduino

uart:
  id: uart_bus
  tx_pin: 13
  rx_pin: 14
  baud_rate: 9600

# get rid of CDC error
esphome:
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

# Enable/Disable logging
logger:
  logs:
    modbus_controller.sensor: WARN
    modbus_controller.output: WARN
    modbus.number: WARN
    esp32.preferences: WARN
    sensor: WARN
    text_sensor: WARN
    dht.sensor: WARN
    switch: WARN
    button: WARN
    number: WARN
  # baud_rate: 0  # <--- super important! for ESP8266

wifi:
  ap:
    ssid: "${name} hotspot"
    password: "configesp"

captive_portal:

# Enable Web server.
web_server:
  port: 80
